services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
    command: botchan start
    ports:
      - 3000:3000

  app-debug:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=debug  
    command: botchan start
    ports:
      - 3000:3000



  ## For quick testing, code are mounted
  backdoor:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './tmp:/tmp'
    command: botchan backdoor
          



  ## For shell access and involve tooling, code are mounted
  shell:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './botchan:/app/home/botchan'
      - './tests:/app/home/tests'
    command: /bin/bash -c "while true; do sleep 3600; done"

