services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
    ports:
      - 3000:3000


  app-debug:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=debug  
    ports:
      - 3000:3000

  backdoor:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './tmp:/tmp'
    command: botchan backdoor
    
  shell:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash -c "while true; do sleep 3600; done"

