FROM python:3.11-slim

WORKDIR /app/home

# Copy and install Python dependencies
COPY requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

# Add the application
ADD fluctlight ./fluctlight
ADD tests ./tests
ADD setup.py ./setup.py
