"""init character table

Revision ID: 30971fed395f
Revises: 
Create Date: 2024-11-24 22:23:38.135098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30971fed395f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('system_prompt', sa.String(length=262144), nullable=True),
    sa.Column('user_prompt', sa.String(length=262144), nullable=True),
    sa.Column('text_to_speech_use', sa.String(length=100), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tts', sa.String(length=64), nullable=True),
    sa.Column('avatar_id', sa.String(length=100), nullable=True),
    sa.Column('background_text', sa.String(length=262144), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
