"""add task_config column to character

Revision ID: f5d85768d810
Revises: 30971fed395f
Create Date: 2024-11-29 21:27:55.517103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d85768d810'
down_revision: Union[str, None] = '30971fed395f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('task_config', sa.String(length=262144), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'task_config')
    # ### end Alembic commands ###
